FROM gcr.io/tensorflow/tensorflow:latest-gpu

RUN apt-get update
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install tensorflow-gpu
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install pillow
RUN pip3 install tqdm
